
stages:
  - pull
  - build
  - deploy

pull:
  stage: pull
  script:
    - sudo git pull .
  tags:
    - kubernetes
  only:
    - master


build:
  stage: build
  script:
    - mvn clean package docker:build -Dmaven.test.skip=true
    - sudo ls -l
  tags:
    - kubernetes
  only:
    - master

deploy:
  stage: deploy
  script:
    - kubectl delete -f ./kubernetes/deployment.yaml
    - kubectl apply -f ./kubernetes/deployment.yaml
  tags:
    - kubernetes
  only:
    - master