stages:
  - pull
  - build

pull:
  stage: pull
  script:
    - cd /usr/local/work/java/SMS-Bombing
    - git pull http://ly%40gitlab.com:12345678@192.168.2.167:8888/dev/SMS-Bombing.git
  tags:
    - my-runner
  only:
    - master


build:
  stage: build
  script:
    - cd /usr/local/work/java
    - mvn clean package docker:build -DskipTests
  tags:
    - my-runner