stages:
  - pull
  - build
  - deploy

.job_template_deploy: &job_k8s_deploy |
  cd kubernetes
  sed -i "s/<REPLICAS_NUM>/$REPLICAS_NUM/g" deployment.yaml
  cat deployment.yaml
  kubectl apply -f deployment.yaml
  kubectl get pod,svc,deploy


pull:
  stage: pull
  script:
    - sudo git pull .
  tags:
    - kubernetes
  only:
    - master


build:
  stage: build
  script:
    - mvn clean package docker:build -Dmaven.test.skip=true
    - sudo ls -l
  tags:
    - kubernetes
  only:
    - master

deploy:
  variables:
    REPLICAS_NUM: 4
  stage: deploy
  script:
    - *job_k8s_deploy
  tags:
    - kubernetes
  only:
    - master