stages:
  - pull
  - build
  - deploy

# 设置全局变量
variables:
  REGISTRY_HOST: 192.168.0.155
  REGISTRY_GROUP: background
  PROJECT_NAME: sms-bombing

.job_template_deploy: &job_k8s_deploy |
  cd kubernetes
  sed -i "s#<REPLICAS_NUM>#$REPLICAS_NUM#g" deployment.yaml
  sed -i "s#<IMAGE_NAME>#$IMAGE_NAME#g" deployment.yaml
  kubectl apply -f deployment.yaml
  kubectl get pod,svc,deploy


pull:
  stage: pull
  script:
    - sudo git pull .
  tags:
    - kubernetes
  only:
    - master


build:
  variables:
    IMAGE_NAME: $REGISTRY_HOST/$REGISTRY_GROUP/$PROJECT_NAME:$CI_BUILD_REF
  stage: build
  script:
    - mvn clean package docker:build -DdockerImageName=$IMAGE_NAME -Dmaven.test.skip=true
  tags:
    - kubernetes
  only:
    - master

deploy:
  variables:
    REPLICAS_NUM: 4
    IMAGE_NAME: $REGISTRY_HOST/$REGISTRY_GROUP/$PROJECT_NAME:$CI_BUILD_REF
  stage: deploy
  script:
    - *job_k8s_deploy
  tags:
    - kubernetes
  only:
    - master